---
name: Github Action - Release It Containerized
description: Github Action to run Release It
author: Juan Carlos Blanco Delgado
branding:
  icon: zap
  color: red
inputs:
  command:
    default: ""
    description: Command to execute Release It
    required: false

  git_email:
    default: ${{ github.actor }}
    description: Git email to run Release It
    required: false

  git_username:
    default: "${{ github.actor }}@users.noreply.github.com"
    description: Git username to run Release It
    required: false

  github_token:
    default: ${{ github.token }}
    description: Github Token to run Release It
    required: false

  gpg_private_key:
    default: ""
    description: GPG Private Key
    required: false

  gpg_private_key_id:
    default: ""
    description: GPG Private Key ID
    required: false

  image_tag:
    default: "latest"
    description: Image tag used to pass specific version of the action
    required: false

  plugins_list:
    default: ""
    description: List of Plugins to run with Release It as comma separated
    required: false

  ssh_passphrase:
    default: ""
    description: SSH Passphrase
    required: false

  ssh_private_key:
    default: ""
    description: SSH Private Key
    required: false

  version:
    default: "latest"
    description: Release It version
    required: false

runs:
  using: composite
  steps:
    - run: |
        docker run \
        -e GITHUB_TOKEN=${GITHUB_TOKEN} \
        -e GIT_DIRECTORY="/app" \
        -e GIT_EMAIL=${GIT_EMAIL} \
        -e GIT_USERNAME="${GIT_USERNAME}" \
        -e GPG_PRIVATE_KEY="${GPG_PRIVATE_KEY}" \
        -e GPG_PRIVATE_KEY_ID="${GPG_PRIVATE_KEY_ID}" \
        -e RELEASE_IT_PLUGINS="${RELEASE_IT_PLUGINS}" \
        -e RELEASE_IT_VERSION="${RELEASE_IT_VERSION}" \
        -e SSH_PASSPHRASE="${SSH_PASSPHRASE}" \
        -e SSH_PRIVATE_KEY="${SSH_PRIVATE_KEY}" \
        -u root \
        -v $PWD:/app \
        ghcr.io/juancarlosjr97/release-it-containerized:${{ inputs.image_tag }} \
        release-it --ci ${{ inputs.command }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GIT_EMAIL: ${{ inputs.git_email }}
        GIT_USERNAME: ${{ inputs.git_username }}
        GPG_PRIVATE_KEY: ${{ inputs.gpg_private_key }}
        GPG_PRIVATE_KEY_ID: ${{ inputs.gpg_private_key_id }}
        RELEASE_IT_PLUGINS: ${{ inputs.plugins_list }}
        RELEASE_IT_VERSION: ${{ inputs.version }}
        SSH_PASSPHRASE: ${{ inputs.ssh_passphrase }}
        SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
      shell: bash
