---
name: Schedule
on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  test:
    uses: ./.github/workflows/tests.yml
    with:
      GIT_EMAIL: ${{ vars.GIT_EMAIL }}
      GIT_USERNAME: ${{ vars.GIT_USERNAME }}
    secrets:
      GITHUB_TOKEN_PROJECT: ${{ secrets.PROJECT_GITHUB_TOKEN }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PRIVATE_KEY_ID: ${{ secrets.GPG_PRIVATE_KEY_ID }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

