---
name: Test
on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Local Test Workflow
        uses: ./.github/workflows/local-template-test-workflow.yaml
        with:
          GITHUB_TOKEN: ${{ secrets.PROJECT_GITHUB_TOKEN }}
          GIT_EMAIL: ${{ vars.GIT_EMAIL }}
          GIT_USERNAME: ${{ vars.GIT_USERNAME }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PRIVATE_KEY_ID: ${{ secrets.GPG_PRIVATE_KEY_ID }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
